services:
  keycloak:
    image: keycloak/keycloak:24.0
    ports:
      - 127.0.0.1:9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./realm:/opt/keycloak/data/import
    command: start-dev --import-realm
