spring:
  application:
    name: api-gateway
  profiles:
    active:
      - dev
      - api-docs

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://keycloak:8080/realms/crm}
        registration:
          gateway-client:
            provider: keycloak
            client-id: ${CLIENT_ID:gateway-client}
            client-secret: ${CLIENT_SECRET:UakJnRBYalsV42peJL7hmHMuydPxMFWd}
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/gateway-client}
  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          - id: crm
            uri: ${CRM_URI:http://localhost:8081}
            predicates:
              - Path=/${CRM_BASE:crm}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: document_store
            uri: ${DOCUMENT_STORE_URI:http://localhost:8082}
            predicates:
              - Path=/${DOCUMENT_STORE_BASE:document_store}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: communication_manager
            uri: ${COMMUNICATION_MANGER_URI:http://localhost:8083}
            predicates:
              - Path=/${COMMUNICATION_MANAGER_BASE:communication_manager}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: ui
            uri: http://localhost:5173
            predicates:
              - Path=/ui/**
          - id: home
            uri: http://localhost:8080
            predicates:
              - Path=/
            filters:
              - RedirectTo=301,http://localhost:8080/ui

server:
  port: ${PORT:8080}

openapi:
  base-url: ${OPENAPI_BASE_URL:http://localhost:8080:${server.port}}
