spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://keycloak:8080/realms/crm}
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: UakJnRBYalsV42peJL7hmHMuydPxMFWd
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/gateway-client}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
