spring:
  application:
    name: api-gateway
  profiles:
    active:
      - dev
      - api-docs
  docker:
    compose:
      lifecycle-management: none
      readiness:
        wait: only_if_started

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://keycloak:8080/realms/crm}
        registration:
          gateway-client:
            provider: keycloak
            client-id: ${CLIENT_ID:gateway-client}
            client-secret: ${CLIENT_SECRET:UakJnRBYalsV42peJL7hmHMuydPxMFWd}
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/gateway-client}
  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          - id: crm
            uri: ${CRM_URI:lb://CRM}
            predicates:
              - Path=/${CRM_BASE:crm}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: document_store
            uri: ${DOCUMENT_STORE_URI:lb://DOCUMENT-STORE}
            predicates:
              - Path=/${DOCUMENT_STORE_BASE:document_store}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: communication_manager
            uri: ${COMMUNICATION_MANGER_URI:lb://COMMUNICATION-MANAGER}
            predicates:
              - Path=/${COMMUNICATION_MANAGER_BASE:communication_manager}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: crm-analytics
            uri: ${CRM_ANALYTICS_URI:lb://CRM-ANALYTICS}
            predicates:
              - Path=/${CRM_ANALYTICS_BASE:crm-analytics}/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: ui
            uri: ${CRM_CLIENT_URI:http://localhost:5173}
            predicates:
              - Path=/ui/**
          - id: home
            uri: ${CURRENT_URI:http://localhost:8080}
            predicates:
              - Path=/
            filters:
              - RedirectTo=301,${CURRENT_URI:http://localhost:8080}/ui

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  port: ${PORT:8080}

openapi:
  base-url: ${OPENAPI_BASE_URL:http://localhost:8080:${server.port}}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  logout-redirect:
    url: ${LOGOUT_REDIRECT_URL:http://localhost:${server.port}}
